App.Schedule.Web.Admin/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace App.Schedule.Web.Admin.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage ="Please enter your email id")]
        [EmailAddress(ErrorMessage ="Please enter a valid email id")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your password")]
        [MinLength(8, ErrorMessage ="Password must be greater than 8 character")]
        [MaxLength(50, ErrorMessage = "Password must be less than 50 character")]
        public string Password { get; set; }
        public bool IsKeepLoggedIn { get; set; }
    }
}

App.Schedule.Web.Admin/Controllers/ForgotController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using App.Schedule.Web.Admin.Models;

namespace App.Schedule.Web.Admin.Controllers
{
    public class ForgotController : LoginBaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(ForgotViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var errMessage = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                return Json(new { status = false, message = errMessage }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var response = await this.AdminService.VerifyLoginCredential(model.Email,"", true);
                if (response != null)
                {
                    return Json(new { status = response.Status, model = "", message = response.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { status = false, message = "There was a problem. Please try again later." }, JsonRequestBehavior.AllowGet);
        }
    }
}

App.Schedule.Web.Admin/Controllers/LoginController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;
using App.Schedule.Domains.ViewModel;

namespace App.Schedule.Web.Admin.Controllers
{
    public class LoginController : LoginBaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var model = new ServiceDataViewModel<LoginViewModel>();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(ServiceDataViewModel<LoginViewModel> model)
        {
            var result = new ResponseViewModel<AdministratorViewModel>();
            try
            {
                if (!ModelState.IsValid)
                {
                    var errMessage = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                    result.Status = false;
                    result.Message = errMessage;
                }
                else
                {
                    if (this.AdminService != null)
                    {
                        var response = await this.AdminService.VerifyLoginCredential(model.Data.Email, model.Data.Password,false);
                        result.Status = response.Status;
                        result.Message = response.Message;
                        result.Data = response.Data;
                        if (response.Status)
                        {
                            var tokenResponse = await this.AdminService.VerifyAndGetAdminAccessToken(model.Data.Email, model.Data.Password);
                            result.Status = tokenResponse.Status;
                            result.Message = tokenResponse.Message;
                            if (tokenResponse.Status)
                            {
                                if (string.IsNullOrEmpty(tokenResponse.Data))
                                {
                                    RedirectToAction("Logout", "Dashboard");
                                }
                                SetAdminSession(response.Data, model.Data.IsKeepLoggedIn, tokenResponse.Data);
                            }
                        }
                    }
                    else
                    {
                        result.Status = false;
                        result.Message = "There was a problem. Please try again later.";
                    }
                }
            }
            catch
            {
                result.Status = false;
                result.Message = "There was a problem. Please try again later.";
            }
            return Json(new { status = result.Status, message = result.Message, data = result.Data }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult TestPage()
        {
            return View();
        }
    }
}

App.Schedule.Web.Admin/Controllers/RegisterController.cs
using System.Linq;
using System.Web.Mvc;
using System.Threading.Tasks;
using App.Schedule.Domains.ViewModel;

namespace App.Schedule.Web.Admin.Controllers
{
    public class RegisterController : RegisterBaseController
    {
        public ActionResult Index()
        {
            var model = new AdministratorViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Index(AdministratorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var errMessage = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(x => x.ErrorMessage));
                return Json(new { status = false, message = errMessage }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var verifyUser = await this.AdminService.VerifyByEmail(model.Email);
                if (verifyUser != null && !verifyUser.Status)
                {
                    var response = await this.AdminService.Add(model);
                    if (response.Status)
                    {
                        return Json(new { status = true, message = "Successfully registered." }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { status = false, message = "There was a problem. Please try again later."}, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { status = false, message = "The email address you have entered is already registered. Did you forgot your login information?" }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

App.Schedule.Web.Admin/Views/Login/Index.cshtml
@using App.Schedule.Domains.ViewModel;
@model ServiceDataViewModel<LoginViewModel>

@{
    ViewBag.Title = "Admin Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<div class="container">
    <div class="row">
        @Html.Partial("~/Views/SubViews/_Error.cshtml", Model)

        @using (Ajax.BeginForm("Index", "Login", new AjaxOptions { }))
        {
            @Html.AntiForgeryToken()
            <div class="absolute-center is-login alert">
                <div id="logo-container">Admin Login</div>
                <div class="col-sm-12 col-md-10 col-md-offset-1">
                    <div class="form-group input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        @Html.EditorFor(model => model.Data.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email Id" } })
                    </div>
                    <div class="form-group input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.EditorFor(model => model.Data.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password", @type = "password" } })
                    </div>
                    <div class="checkbox">
                        <label>
                            @Html.CheckBoxFor(mode => mode.Data.IsKeepLoggedIn, new { htmlAttributes = new { @type = "checkbox" }})  Keep me logged in
                        </label>
                    </div>
                    <div class="form-group">
                        <button type="button" class="btn btn-def btn-block btn-dark" onclick="onSubmit(this,'@Url.Action("Index","Dashboard")');">Login</button>
                    </div>
                    <div class="form-group text-center">
                        <a href="@Url.Action("Index","Forgot")" class="btn btn-link">Forgot?</a> &nbsp; | &nbsp; <a href="@Url.Action("Index", "Register")" class="btn btn-link">Register</a>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="footer-bottom">
        <div>
            &copy; @DateTime.Now.Year. All right reserved by Appointment.
        </div>
    </div>
</div>